---
- name: Copy Cortex XDR agent
  unarchive:
    src: "../../apps/{{ cortex_xdr_linux_agent }}"
    dest: /tmp/cortex
    remote_src: yes

- name: Install Cortex XDR agent
  become: true
  block:
    - name: Create directory for Cortex XDR
      file:
        path: /etc/panw
        state: directory
        mode: 0755

    - name: Copy configuration file
      copy:
        src: /tmp/cortex/config.yaml
        dest: /etc/panw/config.yaml
        mode: 0644

    - name: Copy token file
      copy:
        src: token
        dest: /opt/splunk-edge/var/token
        mode: 0644

    - name: Install Cortex XDR agent
      shell: |
        sh /tmp/cortex/{{ cortex_xdr_linux_agent }} 2>&1 >/dev/null &

- name: Clean up
  file:
    path: /tmp/cortex
    state: absent
