
- import_tasks: create.yml
  when: windows_servers.join_domain == "1" and general.cloud_provider != "local"

- import_tasks: create_local.yml
  when: windows_servers.join_domain == "1" and general.cloud_provider == "local"

- import_tasks: windows-disable-firewall.yml
  when: windows_servers.join_domain == "1"