---

- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - apache2
      - libapache2-mod-security2
      - git
    state: latest
    update_cache: true
  when: install_apache_httpd == "1"

- name: Enable ModSecurity
  shell:
    cmd: sudo a2enmod security2
  when: install_apache_httpd == "1"

- name: Copy recommended conf
  shell:
    cmd: sudo cp /etc/modsecurity/modsecurity.conf-recommended /etc/modsecurity/modsecurity.conf
  when: install_apache_httpd == "1"

- name: Clone OWASP git repository
  shell:
    cmd: $ git clone https://github.com/coreruleset/coreruleset.git
  when: install_apache_httpd == "1"

- name: Enable Core ruleset
  shell:
    cmd: |
      sudo mv coreruleset/crs-setup.conf.example /etc/modsecurity/crs-setup.conf
      sudo mv coreruleset/rules/ /etc/modsecurity/
  when: install_apache_httpd == "1"





- name: reload apache2
  systemd:
    state: restarted
    daemon_reload: yes
    name: apache2