---
# This playbook contains common tasks in this role

- import_tasks: install_phantom_aws.yml
  when: general.cloud_provider == "aws"

- import_tasks: install_phantom_azure.yml
  when: general.cloud_provider == "azure"

- import_tasks: install_phantom_local.yml
  when: general.cloud_provider == "local"

- import_tasks: configure_phantom.yml
  when: phantom_server.phantom_app | regex_search("splunk_soar-unpriv-6")

- import_tasks: configure_phantom_old.yml
  when: phantom_server.phantom_app | regex_search("splunk_soar-unpriv-5")