---
- include_tasks: linux.yml
  when: ansible_os_family == "Debian" and linux_servers.install_red_team_tools == "1"

- include_tasks: windows.yml
  when: ansible_os_family == "Windows" and windows_servers.install_red_team_tools == "1"