---

- import_tasks: windows-disable-defender.yml
- import_tasks: windows-enable-ps-logging.yml
- import_tasks: windows-enable-4688-cmd-line-audit.yml
- import_tasks: install_choco.yml
- include_tasks: install_app_chocolatey.yml
  with_items:
    - "firefox"
    - "git"
    - "notepadplusplus"
    - "7zip"
    - "adobereader"
    - "python"
- import_tasks: advanced_logging.yml
  when: windows_servers.advanced_logging == "1"

